### ISSUE TITLE
OpenLabFramework docker image problems

### ISSUE THREAD

**Issue by msferry** [NanoCAN/OpenLabFramework#19]
Hello,
I have been trying to get the OpenLabFramework docker image to work and have ran into problems.  I am running Ubuntu 14.04.3 on a VirtualBox VM and have successfully installed docker.  When I try to run the OpenLabFramework image I get the output which I have pasted below.  I can browse to the localhost webpage using Firefox but it is just a blank webpage.  Any help that you could give me would be very much appreciated!

*** Running /etc/rc.local...
*** Booting runit daemon...
*** Runit started as PID 10
| Configuring classpath
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/usr/lib/jvm/grails-2.5.0/dist/grails-plugin-log4j-2.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
| Compiling 1 source files.....
Using default settings...
Using default settings...
| Done creating WAR target/OpenLabFramework.war
| Running Grails application
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/usr/lib/jvm/grails-2.5.0/dist/grails-plugin-log4j-2.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
| Error SLF4J: Class path contains multiple SLF4J bindings.
| Error SLF4J: Found binding in [jar:file:/usr/lib/jvm/grails-2.5.0/dist/grails-plugin-log4j-2.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/root/.m2/repository/org/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/root/.grails/2.5.0/projects/OpenLabFramework/tomcat/webapps/OpenLabFramework/WEB-INF/lib/grails-plugin-log4j-2.5.0.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: Found binding in [jar:file:/root/.grails/2.5.0/projects/OpenLabFramework/tomcat/webapps/OpenLabFramework/WEB-INF/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
| Error SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
| Error SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
Using default settings...
Using default settings...
Configuring Spring Security Core ...
... finished configuring Spring Security Core
Database name: fileHSQLDB
Create default settings...
Create default users 'admin' and 'user'...
Create some initial data if necessary.
Exception sending context initialized event to listener instance of class org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener
org.springframework.beans.factory.access.BootstrapException: Error executing bootstraps; nested exception is groovy.lang.MissingPropertyException: No such property: org for class: org.openlab.barcode.BarcodeDataObject
Possible solutions: id, all
	at org.codehaus.groovy.grails.web.context.GrailsContextLoaderListener.initWebApplicationContext(GrailsContextLoaderListener.java:126)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4973)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5467)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: groovy.lang.MissingPropertyException: No such property: org for class: org.openlab.barcode.BarcodeDataObject
Possible solutions: id, all
	at org.openlab.barcode.BarcodeDataObject$__clinit__closure2$_closure3.doCall(BarcodeDataObject.groovy:49)
	at BootStrap.initData(BootStrap.groovy:88)
	at BootStrap$_closure1.doCall(BootStrap.groovy:55)
	at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
	at grails.util.Environment.executeForEnvironment(Environment.java:320)
	at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
	... 4 more
Error listenerStart
Context [/OpenLabFramework] startup failed due to previous errors
The web application [/OpenLabFramework] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
The web application [/OpenLabFramework] registered the JDBC driver [net.sourceforge.jtds.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
The web application [/OpenLabFramework] registered the JDBC driver [com.mysql.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
The web application [/OpenLabFramework] registered the JDBC driver [org.hsqldb.jdbcDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
The web application [/OpenLabFramework] appears to have started a thread named [PoolCleaner[1903678070:1441740739358]] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [HSQLDB Timer @6ae59893] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [net.sf.ehcache.CacheManager@7f54faeb] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.genetracker.vector.Vector.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [openlab.attachments.DataObjectAttachment.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.security.Role.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.security.Requestmap.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.genetracker.AntibioticsWithConcentration.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.genetracker.CellLine.antibiotics.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.genetracker.Recombinant.genes.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [org.openlab.genetracker.CellLine.mediumAdditives.data] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-1] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-2] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-3] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-4] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-5] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-6] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-7] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-8] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-9] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_Worker-10] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [Compass Scheduled Executor Thread [pool-5-thread-1]] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] appears to have started a thread named [quartzScheduler_QuartzSchedulerThread] but has failed to stop it. This is very likely to create a memory leak.
The web application [/OpenLabFramework] created a ThreadLocal with key of type [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2] (value [org.codehaus.groovy.grails.web.converters.configuration.ConvertersConfigurationHolder$2@3f64b0aa]) and a value of type [java.util.HashMap] (value [{}]) but failed to remove it when the web application was stopped. Threads are going to be renewed over time to try and avoid a probable memory leak.
| Server running. Browse to http://localhost:8080/OpenLabFramework
| Server running. Browse to http://localhost:8080/OpenLabFramework

**Comment by mlist** [comment]
Sorry I didn't see the e-mail before. I just committed a fix to the problem and could successfully test the latest automatic build on dockerhub.
