### ISSUE TITLE
Having problems on windows 8

### ISSUE THREAD

**Issue by zurdokero** [NanoCAN/OpenLabFramework#20]
I would really like to get this working on windows 8 for development purpose. I pretty new to grails and I have installed the following.

 jdk-7u80-windows-x64.exe
grails-2.2.5.zip

 I tested out grails creating a helloworld project and everything seems to be working. So I cloned a project into my grails home directory using the command "git clone --recursive https://github.com/NanoCAN/OpenLabFramework.git". I cd into the directory, and executed the grails command, and everything executed fine. Then I executed the ran-app and I get the following error.

| Enter a script name to run. Use TAB for completion:
grails> run-app
| Error Error running script run-app: startup failed:
_GrailsRun_groovy: 19: unable to resolve class org.codehaus.groovy.grails.compil
er.GrailsProjectWatcher
 @ line 19, column 1.
1 error
 (Use --stacktrace to see the full trace)

**Comment by mlist** [comment]
Hi! Thanks for your interest in OpenLabFramework. The latest sources are based on grails 2.5.3 (check out the readme of the repository). Could you try with this version instead?

Alternatively use an older source, e.g. v.1.3.2 from here: https://github.com/NanoCAN/OpenLabFramework/releases

**Comment by zurdokero** [comment]
That worked! Thank you. It did give me a warning but run-app still compiled. This is the error that it throws out.

Error |
SLF4J: Actual binding is of type [org.slf4j.impl.GrailsSlf4jLoggerFactory]
Error |
SLF4J: Class path contains multiple SLF4J bindings.
Error |
SLF4J: Found binding in [jar:file:/C:/Grails/grails-2.5.3/dist/grails-plugin-log
4j-2.5.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
Error |
SLF4J: Found binding in [jar:file:/C:/Users/username/.m2/repository/or
g/slf4j/slf4j-log4j12/1.7.5/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLogger
Binder.class]
Error |
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
