### ISSUE TITLE
Website down?

### ISSUE THREAD

**Issue by ChrisHarrod** [NanoCAN/OpenLabFramework#21]
Folks
I'm on the hunt for a LIM, and would like to test your system, but the [website ](http://www.nanocan.dk/openlabframework/demo) is down.

Is this temporary or have you stopped working on the system?

Chris

**Comment by mlist** [comment]
Hi Chris,

Thanks for your interest. The server was shut down unfortunately but I managed to set up a demo installation at this URL:
https://dockerhts.compbio.sdu.dk/OpenLabFramework/login/auth

user: admin
password: demo0815

**Comment by ChrisHarrod** [comment]
Many thanks!

Any movements on the development of an Android app?

Chris

**Comment by mlist** [comment]
Hi Chris,

I moved on to another position two years ago. I'm doing my best to maintain a working version of the as-is state of OpenLabFramework but new features would have to be implemented by someone else. I'd be happy to provide support for anyone continuing on the project if you know someone. 

Best,
Markus

**Comment by ChrisHarrod** [comment]
Ok – I thought that might be the case.
Thanks for the reply

Cheers
Chris
